### ISSUE TITLE
Tumblr_Crawler 运行报错

### ISSUE THREAD

**Issue by chesterlyd** [sparrow629/Tumblr_Crawler#3]
报错代码：
```
This is thread 145
Traceback (most recent call last):
  File "TumblrCrawler.py", line 218, in <module>
    DownloadAllthepsot(URL)
  File "TumblrCrawler.py", line 126, in DownloadAllthepsot
    task = ThreadTask(PostUrlLists[pageNum])
KeyError: 146
Do you want to Quit? [Y/N]
```
环境配置：
```
pip3 list
beautifulsoup4 (4.5.3)
et-xmlfile (1.0.1)
jdcal (1.3)
lxml (3.7.3)
openpyxl (2.4.7)
pip (9.0.1)
requests (2.13.0)
selenium (3.3.3)
setuptools (28.8.0)
xlrd (1.0.0)
```

**Comment by sparrow629** [comment]
这应该是线程146错了，没启动成功，具体原因从这个报错看不出来，可能是146导致数组越界

**Comment by chesterlyd** [comment]
那有什么办法解决吗

**Comment by sparrow629** [comment]
这个要debug一下，报错信息太简单了。

**Comment by chesterlyd** [comment]
我用pycharm输入网址以后回车就直接打开网页了，没法运行

**Comment by sparrow629** [comment]
粘贴网址后是超链接，删掉几个字母自己补齐，就不是超链接了，可以直接回车

**Comment by chesterlyd** [comment]
用了Debug突然就能下载了

**Comment by chesterlyd** [comment]
就是运行了一个晚上以后卡在下载这里了
```
['150925309774/squirtpussies-squirt-pussies-girls-squirting']
Downloading TumblrMP4download/150925309774.mp4 
http://girls-squirt.tumblr.com/post/150923859004/girls-squirting-tumblr
This is photo
1
[('http://68.media.tumblr.com/0915a95b913c88e2b119ba8245b6764d/tumblr_o5h25wehYL1u6uxico1_500.gif', 'gif')]
Downloading Tumblrimgdownload/150923859004_0.gif 
```
应该是没有下载完，但是没有报错

**Comment by sparrow629** [comment]
可能到这里，你的网断了或者不稳定。

**Comment by guonning** [comment]
python TumblrCrawler.py
  File "TumblrCrawler.py", line 77
    print(page,PostUrlLists[page],sep=' ')
                                     ^
SyntaxError: invalid syntax
